import { Link, useNavigate } from "react-router-dom";
import { ArrowUpRight, Check, ChevronRight, CircleDollarSign, LockKeyhole, ScanLine, Sparkles, TrendingUp, WalletCards } from "lucide-react";
import { useAuth } from "../context/AuthContext";

const features = [
  [ScanLine, "Receipt intelligence", "Turn paper receipts into clean, categorized transactions in seconds.", "Vision AI"],
  [TrendingUp, "A calmer cashflow", "See what is coming in, what is leaving, and what deserves your attention.", "Live insights"],
  [WalletCards, "One clear ledger", "Income, expenses, and savings goals — connected in one considered workspace.", "Everything in one place"],
];

export default function Home() {
  const navigate = useNavigate();
  const { isAuthenticated } = useAuth();
  const start = () => navigate(isAuthenticated ? "/dashboard" : "/signup");
  return <div className="landing-shell">
    <div className="ambient ambient-one" /><div className="ambient ambient-two" />
    <header className="landing-nav"><Link to="/" className="brand"><span className="brand-mark"><Sparkles size={17} /></span><span>SmartExpense <em>AI</em></span></Link><div className="nav-actions">{isAuthenticated ? <Link className="button button-primary button-small" to="/dashboard">Open workspace <ChevronRight size={15} /></Link> : <><Link className="nav-link" to="/login">Sign in</Link><button className="button button-primary button-small" onClick={start}>Get started <ArrowUpRight size={15} /></button></>}</div></header>
    <main>
      <section className="hero-section"><div className="eyebrow"><span className="live-dot" /> Your financial life, made legible</div><h1>Clarity for every<br /><span>spending decision.</span></h1><p className="hero-copy">SmartExpense turns everyday money into a calm, intelligent picture — so you can move through your month with confidence.</p><div className="hero-actions"><button className="button button-primary button-large" onClick={start}>Start for free <ArrowUpRight size={17} /></button><Link className="button button-quiet button-large" to="/login">I already have an account</Link></div><div className="trust-row"><span><Check size={14} /> No credit card</span><span><LockKeyhole size={14} /> Private by design</span><span><CircleDollarSign size={14} /> Built for real life</span></div></section>
      <section className="product-stage" aria-label="SmartExpense product preview"><div className="stage-glow" /><div className="preview-window"><div className="preview-top"><div className="window-dots"><i /><i /><i /></div><span>Overview</span><span className="preview-secure"><LockKeyhole size={12} /> Private workspace</span></div><div className="preview-content"><div className="preview-heading"><div><small>Tuesday, September 02</small><h2>Good morning, Alex</h2></div><div className="preview-avatar">AS</div></div><div className="metric-grid"><div className="metric-card metric-highlight"><small>Available balance</small><strong>$12,840.24</strong><span className="positive"><ArrowUpRight size={13} /> 8.4% this month</span><div className="sparkline"><i /><i /><i /><i /><i /><i /><i /><i /><i /></div></div><div className="metric-card"><small>Monthly inflow</small><strong>$8,250.00</strong><span className="muted">Across 3 income streams</span></div><div className="metric-card"><small>Monthly outflow</small><strong>$3,420.18</strong><span className="muted">12% below your average</span></div></div><div className="preview-lower"><div className="activity-card"><div className="card-title"><span>Recent activity</span><span className="muted">View all</span></div>{[["Whole Foods Market","Groceries","-$84.20"],["Acme Studio","Salary · Sep 01","+$4,250.00"],["Spotify","Subscriptions","-$10.99"]].map(([title,sub,amount]) => <div className="activity-row" key={title}><span className="activity-icon"><WalletCards size={15} /></span><span><b>{title}</b><small>{sub}</small></span><strong className={amount[0] === "+" ? "positive" : ""}>{amount}</strong></div>)}</div><div className="insight-card"><div className="insight-icon"><Sparkles size={15} /></div><small>Smart insight</small><b>You are on track to save<br />$1,120 more this month.</b><span>Based on your last 90 days <ArrowUpRight size={13} /></span></div></div></div></div></section>
      <section className="feature-section"><div className="section-kicker">Designed around your attention</div><h2>Less noise. More knowing.</h2><p className="section-copy">The details are there when you need them, and out of the way when you don't.</p><div className="feature-grid">{features.map(([Icon,title,copy,badge]) => <article className="feature-card" key={title}><div className="feature-icon"><Icon size={19} /></div><span className="feature-badge">{badge}</span><h3>{title}</h3><p>{copy}</p></article>)}</div></section>
    </main><footer className="landing-footer"><span>© {new Date().getFullYear()} SmartExpense AI</span><span>Financial clarity, quietly delivered.</span></footer>
  </div>;
}
